name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: .github/bin/run-tests.bash
